"""Persistence helpers for the sawmill TUI.

Standalone functions for saving and loading TUI state (suppressions, waivers).
The app methods become thin wrappers that update in-memory state.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from sawmill.core.suppress import SuppressConfig, SuppressLoader
from sawmill.core.waiver import WaiverLoader, waiver_to_toml
from sawmill.models.waiver import Waiver
from sawmill.utils.dirs import ensure_sawmill_dir, resolve_sawmill_dir


def save_suppressions(suppressed_ids: set[str], path: Path | None = None) -> Path:
    """Save suppression IDs to a suppress.toml file.

    Args:
        suppressed_ids: Set of message IDs to suppress.
        path: Explicit path to write to. If None, uses .sawmill/suppress.toml.

    Returns:
        The path the file was written to.
    """
    if path is None:
        path = ensure_sawmill_dir() / "suppress.toml"
    SuppressLoader().save(
        SuppressConfig(message_ids=sorted(suppressed_ids)),
        path,
    )
    return path


def load_suppressions(path: Path | None = None) -> SuppressConfig:
    """Load suppressions from .sawmill/suppress.toml.

    Args:
        path: Explicit path. If None, discovers from .sawmill/ or sawmill/.

    Returns:
        SuppressConfig with message_ids and patterns.
    """
    if path is not None:
        return SuppressLoader().load(path)

    sawmill_dir = resolve_sawmill_dir()
    if sawmill_dir is None:
        return SuppressConfig()
    return SuppressLoader().load_from_dir(sawmill_dir)


def resolve_waiver_path(waiver_file_path: Path | None = None) -> Path:
    """Resolve the waiver file path, defaulting to .sawmill/waivers.toml.

    Args:
        waiver_file_path: Explicit path, or None to use the default.

    Returns:
        The resolved waiver file path.
    """
    if waiver_file_path is not None:
        return waiver_file_path
    return ensure_sawmill_dir() / "waivers.toml"


def load_waivers(path: Path) -> list[Waiver]:
    """Load waivers from a TOML file.

    Args:
        path: Path to the waiver file.

    Returns:
        List of Waiver objects, empty list if file doesn't exist.
    """
    if not path.exists():
        return []
    waiver_file = WaiverLoader().load(path)
    return list(waiver_file.waivers)


def save_session_waivers(
    waivers: list[Waiver],
    waiver_path: Path,
    plugin_name: str | None = None,
) -> None:
    """Append session waivers to the waiver file.

    Uses atomic write-to-temp-then-rename to prevent file corruption
    if the process crashes mid-write.

    Args:
        waivers: List of Waiver objects to save.
        waiver_path: Path to the waiver file.
        plugin_name: Optional plugin name for metadata header.
    """
    # If file exists, validate it first
    if waiver_path.exists():
        WaiverLoader().load(waiver_path)  # Validate existing content

    # Build TOML entries for new waivers
    entries = [waiver_to_toml(w) for w in waivers]
    new_content = "\n\n".join(entries) + "\n"

    # Build the full file content (existing + new)
    if waiver_path.exists():
        existing = waiver_path.read_text(encoding="utf-8")
        full_content = existing + "\n" + new_content
    else:
        header = "# Sawmill waiver file\n# Generated by sawmill TUI\n\n"
        if plugin_name:
            header += f'[metadata]\ntool = "{plugin_name}"\n\n'
        full_content = header + new_content

    # Ensure parent directory exists
    waiver_path.parent.mkdir(parents=True, exist_ok=True)

    # Write to temp file in same directory, then atomic rename
    fd, tmp_path = tempfile.mkstemp(
        dir=waiver_path.parent,
        suffix=".tmp",
        prefix=waiver_path.stem,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(full_content)
        os.rename(tmp_path, str(waiver_path))
    except BaseException:
        # Clean up temp file on any failure, then re-raise
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise
